
export const RPCEndPoint = "https://api.roninchain.com/rpc"

export const MarketplaceContractAddress = "0x213073989821f738a7ba3520c3d31a1f9ad31bbd"
export const SLPContractAddress = "0xa8754b9fa15fc18bb59458815510e40a12cd2014"
export const AxieContractAddress = "0x32950db2a7164ae833121501c797d79e7b79d74c"

export const AxieContractABI = [{"constant":false,"inputs":[{"internalType":"address","name":"_from","type":"address"},{"internalType":"address","name":"_to","type":"address"},{"internalType":"uint256","name":"_tokenId","type":"uint256"}],"name":"safeTransferFrom","outputs":[{"internalType":"bool","name":"_success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"uint256","name":"_sireId","type":"uint256"},{"internalType":"uint256","name":"_matronId","type":"uint256"}],"name":"breedAxies","outputs":[{"internalType":"bool","name":"_success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"internalType":"address","name":"_owner","type":"address"},{"internalType":"uint256","name":"_index","type":"uint256"}],"name":"tokenOfOwnerByIndex","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}];
export const SLPContractABI = [{"constant":false,"inputs":[{"internalType":"address","name":"_owner","type":"address"},{"internalType":"uint256","name":"_amount","type":"uint256"},{"internalType":"uint256","name":"_createdAt","type":"uint256"},{"internalType":"bytes","name":"_signature","type":"bytes"}],"name":"checkpoint","outputs":[{"internalType":"uint256","name":"_balance","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"_to","type":"address"},{"internalType":"uint256","name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"_success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"}];
export const MarketplaceABI = [{"inputs":[{"indexed":false,"internalType":"address","name":"_seller","type":"address"},{"indexed":false,"internalType":"uint256","name":"_listingIndex","type":"uint256"},{"indexed":false,"internalType":"uint256[]","name":"_startingPrices","type":"uint256[]"},{"indexed":false,"internalType":"uint256[]","name":"_endingPrices","type":"uint256[]"},{"indexed":false,"internalType":"address[]","name":"_exchangeTokens","type":"address[]"},{"indexed":false,"internalType":"uint256[]","name":"_durations","type":"uint256[]"},{"indexed":false,"internalType":"uint256","name":"_startingTimestamps","type":"uint256"}],"name":"AuctionCreated","type":"event"},{"inputs":[{"internalType":"uint8[]","name":"_tokenTypes","type":"uint8[]"},{"internalType":"address[]","name":"_tokenAddresses","type":"address[]"},{"internalType":"uint256[]","name":"_tokenNumbers","type":"uint256[]"},{"internalType":"uint256[]","name":"_startingPrices","type":"uint256[]"},{"internalType":"uint256[]","name":"_endingPrices","type":"uint256[]"},{"internalType":"address[]","name":"_exchangeTokens","type":"address[]"},{"internalType":"uint256[]","name":"_durations","type":"uint256[]"}],"name":"createAuction","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_seller","type":"address"},{"internalType":"address","name":"_token","type":"address"},{"internalType":"uint256","name":"_bidAmount","type":"uint256"},{"internalType":"uint256","name":"_listingIndex","type":"uint256"},{"internalType":"uint256","name":"_listingState","type":"uint256"}],"name":"settleAuction","outputs":[],"stateMutability":"nonpayable","type":"function"}];







